
# cloudos_test@kynetx.com/for_testing
eci: 07E6569E-6CE9-11E3-81D7-05AA87B7806A 
rules_engine: kibdev.kobj.net

test_1:
   desc: "Dropbox module test"
   domain: test
   type: get_request_token
   attributes:
     foo: bar
   rids:
    - b16x6.prod
     